pxSurvey/pxSurvey/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('survey.urls', namespace='survey')),

    # View URLs
    url(r'^fobi/', include('fobi.urls.view')),

    # Edit URLs
    url(r'^fobi/', include('fobi.urls.edit')),

    # DB Store plugin URLs
    url(r'^fobi/plugins/form-handlers/db-store/',
        include('fobi.contrib.plugins.form_handlers.db_store.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pxSurvey/survey/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    #url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^dashboard/$', DashboardView.as_view(), name='dashboard'),

    url(r'^accounts/login/$', AdminLogInView.as_view(), name='adminLogIn'),
    url(r'^accounts/logout/$', AdminLogOutView.as_view(), name='adminLogOut'),


    url(r'^staff/list/$', StaffListView.as_view(), name='staffList'),
    url(r'^form/list/$', FormEntryListView.as_view(), name='formList'),
    url(r'^form/(?P<pk>\d+)/chart/$',
        FormEntryChartView.as_view(), name='formChart'),
    url(r'^staff/create/$',
        StaffCreateView.as_view(), name='staffCreate'),
    url(r'^staff/(?P<pk>\d+)/email-change/$',
        StaffEmailChangeView.as_view(), name='staffEmailChange'),
    url(r'^staff/(?P<pk>\d+)/toggle-group/$',
        StaffToggleGroupView.as_view(), name='staffToggleGroup')
]

pxSurvey/survey/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Timestampable(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()

pxSurvey/survey/forms.py
from django import forms
from django.utils import timezone
from datetime import timedelta
from .models import *
from django.contrib.auth.models import User


class LogInForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'required': 'true',
            'id': 'username',
        }))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'required': 'true',
            'id': 'password',

        }))


class StaffForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})


class EmailForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'required': 'true',
            'id': 'email',
        }))

pxSurvey/survey/views.py
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView, FormView
from django.shortcuts import render, redirect, get_object_or_404
# from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
import random
import string

from .models import *
from .forms import *

from fobi.models import *
from fobi.contrib.plugins.form_handlers.db_store.models import *

from django.contrib.auth.mixins import LoginRequiredMixin


class LoginMixin(LoginRequiredMixin):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'


class AdminLogInView(View):
    def get(self, request):
        form = LogInForm()
        context = {
            'form': form,
        }
        return render(request, 'survey/adminLogIn.html', context)

    def post(self, request):
        form = LogInForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user and user.is_active:
                messages.success(request, "Logged In Successfully")
                login(request, user)
                return redirect('survey:dashboard')
        messages.warning(request, "Log In Failure")
        context = {
            'form': form,
        }
        return render(request, 'survey/adminLogIn.html', context)


class AdminLogOutView(LoginMixin, View):

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated():
            logout(request)
        messages.success(request, "Logged Out Successfully")
        return redirect('survey:adminLogIn')


class DashboardView(LoginMixin, TemplateView):
    template_name = 'survey/dashboard.html'


class StaffCreateView(LoginMixin, SuccessMessageMixin, CreateView):
    model = User
    template_name = 'survey/staffCreate.html'
    form_class = StaffForm
    success_url = reverse_lazy("survey:staffList")
    success_message = "Staff Successfully Added"

    def post(self, request, *args, **kwargs):
        form = StaffForm(request.POST or None)
        if form.is_valid():
            user = form.save(commit=False)
            password = ''.join([random.choice(string.ascii_letters + string.digits + string.punctuation)
                                for n in range(18)])
            user.set_password(password)
            user.save()
            grp = Group.objects.get(name='Staff')
            grp.user_set.add(user)
            messages.success(request, "Staff Added Successfully")
        return HttpResponseRedirect(self.success_url)


class StaffEmailChangeView(LoginMixin, SuccessMessageMixin, FormView):
    template_name = 'survey/staffEmailChange.html'
    form_class = EmailForm
    success_url = reverse_lazy("survey:staffList")
    success_message = "Email Successfully Changed"

    def dispatch(self, request, *args, **kwargs):
        self.user = User.objects.get(pk=kwargs['pk'])
        return super(StaffEmailChangeView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form, **kwargs):
        email = form.cleaned_data.get('email')
        self.user.email = email
        self.user.save()
        return super(StaffEmailChangeView, self).form_valid(form, **kwargs)


class StaffToggleGroupView(LoginMixin, View):
    def get(self, request, **kwargs):
        pk = kwargs['pk']
        user = User.objects.get(pk=pk)
        if user.groups.all().first().name == 'Staff':
            grp = Group.objects.get(name='Staff')
            grp.user_set.remove(user)
            grp = Group.objects.get(name='Admin')
            grp.user_set.add(user)
        else:
            grp = Group.objects.get(name='Admin')
            grp.user_set.remove(user)
            grp = Group.objects.get(name='Staff')
            grp.user_set.add(user)
        return redirect(reverse_lazy("survey:staffList"))


class StaffListView(LoginMixin, ListView):
    model = User
    template_name = 'survey/staffList.html'
    context_object_name = 'staffs'


class FormEntryListView(LoginMixin, ListView):
    model = FormEntry
    template_name = 'survey/formList.html'
    context_object_name = 'formEntries'


class FormEntryChartView(LoginMixin, View):
    def get(self, request, **kwargs):
        pk = kwargs['pk']
        formEntry = get_object_or_404(FormEntry, pk=pk)
        if SavedFormDataEntry.objects.filter(form_entry=formEntry):
            savedFormEntiers = SavedFormDataEntry.objects.filter(
                form_entry=formEntry)
        print(dir(formEntry))
        context = {
        }
        return render(request, 'survey/formCharts.html', context)

pxSurvey/templates/fobi/generic/_base.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="en"{% block html-attributes %}{% endblock html-attributes %}>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block favicon %}
    <link rel="shortcut icon" href="{% block favicon-image %}{% endblock favicon-image %}">
    {% endblock favicon %}

    <title>{% block head_title %}Survey Management System{% endblock %}</title>
    {% include "layouts/admin/include/head.html" %}
    <style type="text/css">
      .help-block{
        top: 20px !important;
      }
    </style>

    {% block stylesheets %}
    {#<!-- Additional core CSS files that somehow can't be put into the python theme -->#}
    {% endblock stylesheets %}

    {% block extra-stylesheets %}{% endblock extra-stylesheets %}

    {% block head-javascripts %}
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    {% endblock head-javascripts %}

    {% block extra-head-javascripts %}{% endblock extra-head-javascripts %}

    {% block extrahead %}{% endblock extrahead %}
    {% block extra_head %}
    {% endblock %}
  </head>

  <body class="menubar-hoverable header-fixed full-content">
    <header id="header" >
        <div class="headerbar">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="headerbar-left">
                <ul class="header-nav header-nav-options">
                    <li class="header-nav-brand" >
                        <div class="brand-holder">
                            <a href="{% url 'survey:dashboard' %}">
                                <span class="text-lg text-bold text-primary">Survey Management System</span>
                            </a>
                        </div>
                    </li>
                    <li>
                        <a class="btn btn-icon-toggle menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                            <i class="fa fa-bars"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="headerbar-right">
                <ul class="header-nav header-nav-options">
                    <li>
                        <!-- Search form -->
                        <form class="navbar-search" role="search">
                            <div class="form-group">
                                <input type="search" class="form-control" name="headerSearch" placeholder="Enter your keyword">
                            </div>
                            <button type="submit" class="btn btn-icon-toggle ink-reaction"><i class="fa fa-search"></i></button>
                        </form>
                    </li>
                </ul><!--end .header-nav-options -->
                <ul class="header-nav header-nav-profile">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle ink-reaction" data-toggle="dropdown">
                            <img src="{% static 'assets/img/avatar1.jpg' %}" alt="" />
                            <span class="profile-info">
                                {{request.user.get_full_name}}
                                <small>{{request.user.username}} </small>
                            </span>
                        </a>
                        <ul class="dropdown-menu animation-dock">
                            <li><a href="#"  data-toggle="modal" data-target="#logOutModal"><i class="fa fa-fw fa-power-off text-danger"></i> Logout</a></li>
                        </ul><!--end .dropdown-menu -->
                    </li><!--end .dropdown -->
                </ul><!--end .header-nav-profile -->
            </div><!--end #header-navbar-collapse -->
        </div>
    </header>
    <!-- END HEADER-->

    <div class="modal fade" id="logOutModal" tabindex="-1" role="dialog" aria-labelledby="logOutModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="simpleModalLabel">Log Out</h4>
                </div>
                <div class="modal-body">
                    <p>Do you want to logout?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary"><a href="{% url 'survey:adminLogOut' %}"  style="text-decoration:none;">Logout</a></button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- END SIMPLE MODAL MARKUP -->

  {% block before-main-wrapper %}{% endblock %}

  {% block main-wrapper %}
  <div id="base">

    {% block main-content-wrapper %}
        {% if messages %}
        {% for message in messages %}
        <div id="toast-container" class="toast-bottom-right" aria-live="polite" role="alert">
           <div class="toast toast-{{message.tags}}">
               <div class="toast-message">{{ message }}</div>
           </div>
       </div>
       {% endfor %}
       {% endif %}

      {% block messages-wrapper %}
      {% include fobi_theme.messages_snippet_template_name %}
      {% endblock messages-wrapper %}
      {% block main-content %}
        <div id="content">
        <section>
          <div class="section-body contain-lg">
            <div class="card">
              <div class="card-body">
              {% block content-wrapper %}
              {% block content %}
              {% endblock %}
              {% endblock content-wrapper %}
              </div>
            </div>
          </div>
        </section>
        </div><!--end #content-->
      {% endblock main-content %}
    {% endblock main-content-wrapper %}
    {% block menubar%}
    <!-- BEGIN MENUBAR-->
    <div id="menubar" class="menubar-inverse ">
        <div class="menubar-fixed-panel">
            <div>
                <a class="btn btn-icon-toggle btn-default menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                    <i class="fa fa-bars"></i>
                </a>
            </div>
            <div class="expanded">
                <a href="{% url 'survey:dashboard' %}">
                    <span class="text-lg text-bold text-primary ">Survey Management System</span>
                </a>
            </div>
        </div>
        <div class="menubar-scroll-panel">

            <!-- BEGIN MAIN MENU -->
            <ul id="main-menu" class="gui-controls">

                <li>
                    <a href="{% url 'survey:dashboard' %}" id="dashboard">
                        <div class="gui-icon"><i class="fa fa-home"></i></div>
                        <span class="title">Dashboard</span>
                    </a>
                </li><!--end /menu-li -->
                <!-- END DASHBOARD -->

                <li>
                    <a href="{% url 'fobi.dashboard' %}" id="forms">
                        <div class="gui-icon"><i class="fa fa-gears"></i></div>
                        <span class="title">Forms</span>
                    </a>
                </li><!--end /menu-li -->
                <!--
                <li>
                    <a href="{% url 'fobi.form_wizards_dashboard' %}" id="wizards">
                        <div class="gui-icon"><i class="fa fa-users"></i></div>
                        <span class="title">Wizards</span>
                    </a>
                </li>--><!--end /menu-li -->

                <li>
                    <a href="{% url 'survey:staffList' %}" id="staffs">
                        <div class="gui-icon"><i class="fa fa-users"></i></div>
                        <span class="title">Staffs</span>
                    </a>
                </li><!--end /menu-li -->


            </ul><!--end .main-menu -->
            <!-- END MAIN MENU -->

            <div class="menubar-foot-panel">
                <small class="no-linebreak hidden-folded">
                    <span class="opacity-75">Copyright &copy; 2016</span> <strong>Prixa</strong>
                </small>
            </div>
        </div><!--end .menubar-scroll-panel-->
    </div><!--end #menubar-->
    <!-- END MENUBAR -->
    {% endblock menubar %}

</div>
  {% endblock main-wrapper %}

  {% include "layouts/admin/include/javascript.html" %}
    <script type="text/javascript">
        $(function(){
            {% if messages %}
            toastr.clear();
            {% for message in messages %}
            toastr.options.closeButton = true;
            toastr.options.progressBar = true;
            toastr.options.debug = false;
            toastr.options.positionClass = 'toast-bottom-right';
            toastr.options.showDuration = 333;
            toastr.options.hideDuration = 333;
            toastr.options.timeOut = 4000;
            toastr.options.extendedTimeOut = 4000;
            toastr.options.showEasing = 'swing';
            toastr.options.hideEasing = 'swing';
            toastr.options.showMethod = 'slideDown';
            toastr.options.hideMethod = 'slideUp';
            toastr.{{message.tags}}('{{message}}', '');
            {% endfor %}
            {% endif %}
        });

    </script>
    {% block extra_js %}
    {% endblock extra_js %}

  {% block javascripts %}
  {% endblock javascripts %}

    <script src="/static/jquery-ui/js/jquery-ui-1.10.4.custom.min.js"></script>

    <script src="/static/js/jquery.slugify.js"></script>

    <script src="/static/js/fobi.core.js"></script>

    <script src="/static/bootstrap3/js/bootstrap3_fobi_extras.js"></script>

  </body>
</html>

pxSurvey/templates/fobi/generic/add_form_element_entry_ajax.html
{% extends fobi_theme.form_edit_ajax %}

{% load i18n %}

{% block form_page_title %}
{% blocktrans with form_element_plugin.name as plugin_name %}Add "{{ plugin_name }}" element to the form{% endblocktrans %}
{% endblock form_page_title %}

{% block form_extra_attrs %} id="form_element_entry_form" {% endblock %}

{% block form_primary_button_text %}{% trans "Add" %}{% endblock %}

pxSurvey/templates/fobi/generic/add_form_handler_entry_ajax.html
{% extends fobi_theme.form_edit_ajax %}

{% load i18n %}

{% block form_page_title %}
{% blocktrans with form_handler_plugin.name as plugin_name %}Add "{{ plugin_name }}" handler to the form{% endblocktrans %}
{% endblock form_page_title %}

{% block form_primary_button_text %}{% trans "Add" %}{% endblock %}

pxSurvey/templates/fobi/generic/create_form_entry_ajax.html
{% extends fobi_theme.form_edit_ajax %}

{% load i18n %}

{% block form_page_title %}
{% trans "Create form" %}
{% endblock form_page_title %}

{% block form_primary_button_text %}{% trans "Add" %}{% endblock %}

pxSurvey/templates/fobi/generic/edit_form_element_entry_ajax.html
{% extends fobi_theme.form_edit_ajax %}

{% load i18n %}

{% block form_page_title %}
{% blocktrans with form_element_plugin.name as plugin_name %}Edit "{{ plugin_name }}" element of the form{% endblocktrans %}
{% endblock form_page_title %}

{% block form_primary_button_text %}{% trans "Submit" %}{% endblock %}

{% block form_extra_attrs %} id="form_element_entry_form" {% endblock %}

pxSurvey/templates/fobi/generic/edit_form_entry.html
{% extends fobi_theme.base_edit_template %}

{% load i18n %}

{% block page-title %}{% trans "Edit form entry" %}{% endblock page-title %}

{% block navbar-menu-right-content %}
            <li class="active"><a href="{% url 'fobi.dashboard' %}">{% trans "Forms" %}</a></li>
            <li><a href="{% url 'fobi.form_wizards_dashboard' %}">{% trans "Wizards" %}</a></li>
{% endblock navbar-menu-right-content %}

{% block navbar-menu-content %}
<li class="active"><a href="{% url 'fobi.edit_form_entry' form_entry.pk %}">{% trans "Edit" %}</a></li>
<li><a href="{% url 'fobi.view_form_entry' form_entry.slug %}">{% trans "View" %}</a></li>
{% comment %}
<li class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
  {% trans "Your forms" %} <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    {% for entry in all_form_entries %}
    <li>
      <a href="{% url 'fobi.edit_form_entry' entry.pk %}">{{ entry.name }}</a>
    </li>
    {% endfor %}
  </ul>
</li>
{% endcomment %}
{% endblock navbar-menu-content %}

{% block main-content-inner-attrs %}{% endblock main-content-inner-attrs %}

{% block content-wrapper %}
    {% include fobi_theme.edit_form_entry_ajax_template %}
{% endblock content-wrapper %}

{% block sidebar-wrapper %}
{% endblock sidebar-wrapper %}

pxSurvey/templates/fobi/generic/snippets/form_non_field_and_hidden_errors_snippet.html
    {{ form.non_field_errors.as_text }}
    {{ form_hidden_fields_errors.as_text }}

pxSurvey/templates/fobi/generic/snippets/messages_snippet.html
    {% if messages %}
    <div class="{% block alert_html_class %}alert alert-info{% endblock alert_html_class %}">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
    {% endif %}

pxSurvey/templates/survey/formList.html
{% extends 'layouts/admin/base.html' %}
{% load staticfiles %}

{% block head_title %}
    {{block.super}} | Staff List
{% endblock %}

{%block extra_head %}
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/jquery.dataTables.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.colVis.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.tableTools.css' %}" />
{% endblock %}

{% block content %}
<section>
<div class="section-body">
<h2>Staff List</h2>
    <div class="card">
        <div class="card-body">
        <a style="margin-bottom: 10px;" class="btn ink-reaction btn-floating-action btn-primary pull-right" href ="{% url 'survey:staffCreate' %}"><i class="fa fa-plus"></i></a>
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table id="datatable1" class="table table-striped table-hover" style="margin-bottom:20px">
                            <thead>
                                <tr>
                                    <th class="sort-alpha">Form Name</th>
                                    <th class="sort-alpha">Form Slug</th>
                                    <th>Actions</th>
                            </thead>
                            <tbody>
                                {% for formEntry in formEntries %}
                                    <tr>
                                        <td>{{formEntry.name}}</td>
                                        <td>{{formEntry.public}}</td>
                                        <td>
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-sm">Action</button>
                                                <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown"><i class="fa fa-caret-down"></i></button>
                                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                                    <li><a ><i class="fa fa-trash"></i> Delete</a></li>
                                                </ul>
                                            </div></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div><!--end .table-responsive -->
                </div><!--end .col -->
            </div><!--end .row -->
        </div>
    </div>
</div>
<br/>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#staff').addClass('active')
</script>>
<script src="{% static 'assets/js/libs/DataTables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/ColVis/js/dataTables.colVis.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/TableTools/js/dataTables.tableTools.min.js' %}"></script>
<script type='text/javascript'>
(function(namespace, $) {
    "use strict";
    var DemoTableDynamic = function() {
        var o = this;
        $(document).ready(function() {
            o.initialize();
        });

    };
    var p = DemoTableDynamic.prototype;
    p.initialize = function() {
        this._initDataTables();
    };
    p._initDataTables = function() {
        if (!$.isFunction($.fn.dataTable)) {
            return;
        }
        this._createDataTable1();
    };

    p._createDataTable1 = function() {
        $('#datatable1').DataTable({
            "dom": 'lCfrtip',
            "order": [],
            "colVis": {
                "buttonText": "Columns",
                "overlayFade": 0,
                "align": "right"
            },
            "language": {
                "lengthMenu": '_MENU_ entries per page',
                "search": '<i class="fa fa-search"></i>',
                "paginate": {
                    "previous": '<i class="fa fa-angle-left"></i>',
                    "next": '<i class="fa fa-angle-right"></i>'
                }
            }
        });
    };
    namespace.DemoTableDynamic = new DemoTableDynamic;
}(this.materialadmin, jQuery)); // pass in (namespace, jQuery):
</script>
{% endblock %}

pxSurvey/templates/survey/staffList.html
{% extends 'layouts/admin/base.html' %}
{% load staticfiles %}

{% block head_title %}
    {{block.super}} | Staff List
{% endblock %}

{%block extra_head %}
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/jquery.dataTables.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.colVis.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.tableTools.css' %}" />
{% endblock %}

{% block content %}
<section>
<div class="section-body">
<h2>Staff List</h2>
    <div class="card">
        <div class="card-body">
        <a style="margin-bottom:10px;margin-right:5px;margin-left:5px; z-index:1000;" class="btn ink-reaction btn-floating-action btn-primary pull-right" href ="{% url 'survey:staffCreate' %}"><i class="fa fa-plus"></i></a>
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table id="datatable1" class="table table-striped table-hover" style="margin-bottom:20px">
                            <thead>
                                <tr>
                                    <th class="sort-numeric">Id</th>
                                    <th class="sort-alpha">Username</th>
                                    <th class="sort-alpha">Full Name</th>
                                    <th class="sort-alpha">Email</th>
                                    <th class="sort-alpha">Group</th>
                                    <th>Actions</th>
                            </thead>
                            <tbody>
                                {% for staff in staffs %}
                                    <tr>
                                        <td>{{staff.id}}</td>
                                        <td>{{staff.username}}</td>
                                        <td>{{staff.get_full_name}}</td>
                                        <td>{{staff.email}}</td>
                                        <td><a href="{% url 'survey:staffToggleGroup' staff.id %}">{{staff.groups.first}}</a></td>
                                        <td>
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-sm">Action</button>
                                                <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown"><i class="fa fa-caret-down"></i></button>
                                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                                    <li><a href="{% url 'survey:staffToggleGroup' staff.id %}"><i class="fa fa-toggle-on"></i> Toggle Group</a></li>
                                                    <li><a ><i class="fa fa-trash"></i> Delete</a></li>
                                                </ul>
                                            </div></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div><!--end .table-responsive -->
                </div><!--end .col -->
            </div><!--end .row -->
        </div>
    </div>
</div>
<br/>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#staff').addClass('active')
</script>>
<script src="{% static 'assets/js/libs/DataTables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/ColVis/js/dataTables.colVis.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/TableTools/js/dataTables.tableTools.min.js' %}"></script>
<script type='text/javascript'>
(function(namespace, $) {
    "use strict";
    var DemoTableDynamic = function() {
        var o = this;
        $(document).ready(function() {
            o.initialize();
        });

    };
    var p = DemoTableDynamic.prototype;
    p.initialize = function() {
        this._initDataTables();
    };
    p._initDataTables = function() {
        if (!$.isFunction($.fn.dataTable)) {
            return;
        }
        this._createDataTable1();
    };

    p._createDataTable1 = function() {
        $('#datatable1').DataTable({
            "dom": 'lCfrtip',
            "order": [],
            "colVis": {
                "buttonText": "Columns",
                "overlayFade": 0,
                "align": "right"
            },
            "language": {
                "lengthMenu": '_MENU_ entries per page',
                "search": '<i class="fa fa-search"></i>',
                "paginate": {
                    "previous": '<i class="fa fa-angle-left"></i>',
                    "next": '<i class="fa fa-angle-right"></i>'
                }
            }
        });
    };
    namespace.DemoTableDynamic = new DemoTableDynamic;
}(this.materialadmin, jQuery)); // pass in (namespace, jQuery):
</script>
{% endblock %}